on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Debug SSH Key Length
      run: echo "SSH key length: ${{ secrets.EC2_SSH_KEY }}" | wc -c

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        ssh_args: -vvv
        script: |
          cd /home/ec2-user/ResearchBuddy
          git pull origin main
          docker compose down
          docker compose build
          docker compose up -d
